config/routes.rb
Rails.application.routes.draw do
  root 'courses#index'

  resources :users
  resources :courses do
    resources :enrollments, only: [:index, :new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :enrollements, dependent: :destroy
  has_many :users, through: :enrollements
end

app/models/enrollement.rb
class Enrollement < ApplicationRecord
  belongs_to :user
  belongs_to :course
end

app/models/user.rb
class User < ApplicationRecord
  has_many :enrollements, dependent: :destroy
  has_many :courses, through: :enrollements
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :destroy]

  def index
    @courses = Course.all
  end

  def show
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)
    if @course.save
      redirect_to @course
    else
      render :new
    end
  end

  def destroy
    @course.destroy
    redirect_to courses_path
  end

  private
    def course_params
      params.require(:course).permit(:name)
    end

    def set_course
      @course = Course.find(params[:id])
    end
end

app/controllers/enrollements_controller.rb
class EnrollementsController < ApplicationController
  before_action :set_course

  def index
    @teachers = @course.enrollements.where(role: 'Teacher')
    @tas = @course.enrollements.where(role: 'Ta')
    @students = @course.enrollements.where(role: 'Students')
  end

  def new
    @enrollement = @course.enrollements.new
  end

  def create
    @enrollement = @course.enrollements.new(enrollement_params)
    if @enrollement.save
      redirect_to course_enrollements_path
    else
      render :new
    end
  end

  def destroy
    enrollement = @course.enrollements.find(params[:id])
    enrollement.destroy
    redirect_to course_enrollements_path
  end

  private 
    def enrollement_params
      params.require(:enrollement).permit(:role, :user_id)
    end 

    def set_course
      @course = Course.find(params[:id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render :new
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end

  private 
    def user_params
      params.require(:user).permit(:first_name, :last_name)
    end

    def set_user
      @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/enrollements_helper.rb
module EnrollementsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/courses/index.html.erb
<h1>All Courses</h1>

<%= link_to 'add Course', new_course_path %>

<% @courses.each do |course| %>
  <%= link_to course.name, course %>
<% end %>

app/views/courses/new.html.erb
<h1>Courses form</h1>

<%= form_for @course do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true %>

  <%= f.submit %>
<% end %>

app/views/courses/show.html.erb
<h1>Courses#show</h1>
<p>Find me in app/views/courses/show.html.erb</p>

app/views/enrollements/index.html.erb
<h1>Enrollements#index</h1>
<p>Find me in app/views/enrollements/index.html.erb</p>

app/views/enrollements/new.html.erb
<h1>Enrollements#new</h1>
<p>Find me in app/views/enrollements/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Canvas</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h1>All Users</h1>

<%= link_to 'Add User', new_user_path %>

<% @users.each do |user| %>
  <%= link_to user.first_name, user %>
<% end %>

app/views/users/new.html.erb
<h1>Users form</h1>

<%= form_for @user do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name, required: true %>

  <%= f.label :last_name %>
  <%= f.text_field :last_name %>

  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<%= @user.first_name %> - <%= @user.last_name %>

<% @user.courses.each do |course| %>
  <%= link_to course.name, course %>
<% end %>

<%= link_to 'Delete User', @user, method: :delete %>